### ISSUE TITLE
pre-commit hook always shows failed

### ISSUE THREAD

**Issue by NoFuchsGavin** [extenda/pre-commit-hooks#19]
**.pre-commit-config.yaml**

```
default_language_version:
  python: python3.9

repos:
-  repo: https://github.com/extenda/pre-commit-hooks.git
   rev: v0.4
   hooks:
     - id: google-java-formatter
```

Running the pre-commit manually it always shows up "failed" even though the file is successfully formatted:

Command: pre-commit run --files your/path/to/any/java/file.java

![image](https://user-images.githubusercontent.com/26583027/118645178-e8208480-b7de-11eb-9acc-32d2cf38351d.png)
